version: '3.8'

services:
  mailchimp-migrator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailchimp-to-mailerlite-migrator
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - migrator-network

networks:
  migrator-network:
    driver: bridge