# Development-specific configuration
spring:
  devtools:
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
      additional-paths: src/main/resources/templates,src/main/resources/static
    livereload:
      enabled: true
      port: 35729
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  web:
    resources:
      cache:
        period: 0
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
        - classpath:/META-INF/resources/webjars/

# Logging configuration for development
logging:
  level:
    digital.pragmatech: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"

# Development server configuration
server:
  port: 8080
  servlet:
    context-path: /

# Migration configuration for development (faster for testing)
migration:
  batch-size: 100
  rate-limit:
    requests-per-minute: 300
    retry:
      max-attempts: 2
      initial-delay: 500ms
      max-delay: 2s