spring:
  application:
    name: mailchimp-to-mailerlite-migrator

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
    scheduling:
      pool:
        size: 5

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    digital.pragmatech: DEBUG
    org.springframework.web: INFO
    org.springframework.web.client.RestClient: DEBUG

migration:
  batch-size: 500
  retry:
    max-attempts: 3
    backoff-delay: 1000
  rate-limit:
    mailchimp:
      connections: 10
      timeout: 120000
    mailerlite:
      requests-per-minute: 120

api:
  mailchimp:
    base-url: https://{datacenter}.api.mailchimp.com/3.0
    default-api-key: ${MAILCHIMP_API_KEY:}
  mailerlite:
    base-url: https://connect.mailerlite.com/api
    default-api-token: ${MAILERLITE_API_TOKEN:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  info:
    build:
      enabled: true
    git:
      mode: full
  health:
    diskspace:
      enabled: true
