name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
      
    - name: Set version from tag
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        ./mvnw versions:set -DnewVersion=$VERSION -DgenerateBackupPoms=false
        
    - name: Build and package
      run: ./mvnw clean package -DskipTests
      
    - name: Create release directory
      run: |
        mkdir -p release
        cp target/*.jar release/
        cp README.md release/
        cp run.sh release/
        
    - name: Create release archive
      run: |
        cd release
        tar -czf mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.tar.gz *
        zip -r mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.zip *
        
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: release/mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.tar.gz
        asset_name: mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.tar.gz
        asset_content_type: application/gzip
        
    - name: Upload release assets (ZIP)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: release/mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.zip
        asset_name: mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.zip
        asset_content_type: application/zip
        
    - name: Upload JAR artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: target/mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.jar
        asset_name: mailchimp-to-mailerlite-migrator-${{ env.VERSION }}.jar
        asset_content_type: application/java-archive